=== consultant-1379/o1-fm-transformation/o1-support-cbp-oi-fm-transformation-jar/src/main/resources/snmp-mediation-config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="snmp-mediation-config" type="snmpMediationConfig"/>

  <xs:complexType name="snmpMediationConfig">
    <xs:sequence>
      <xs:element name="network-element" type="networkElementConfig" minOccurs="0"/>
      <xs:element name="properties" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="property" type="propertyConfig" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="networkElementConfig">
    <xs:sequence>
      <xs:element name="transformer-config" type="xs:string" minOccurs="0"/>
      <xs:element name="mibs" type="xs:string" minOccurs="0"/>
      <xs:element name="alarms-get-config" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="alarm-entry-config" type="alarmEntryConfig" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:choice minOccurs="0">
        <xs:element name="heartbeat-push-config" type="heartBeatPushConfig"/>
        <xs:element name="heartbeat-pull-config" type="heartBeatPullConfig"/>
      </xs:choice>
      <xs:element name="properties" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="property" type="propertyConfig" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="type" type="xs:string"/>
    <xs:attribute name="version" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="alarmEntryConfig">
    <xs:sequence>
      <xs:element name="snmp-table" type="snmpTableConfig" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="snmp-last-seq-no" type="snmpObjectConfig" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="description" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="snmpTableConfig">
    <xs:sequence>
      <xs:element name="snmp-field" type="snmpObjectConfig" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="oid" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="snmpObjectConfig">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="oid" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="heartBeatPushConfig">
    <xs:sequence>
      <xs:element name="heartbeat-interval-config" type="heartBeatIntervalConfig" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="heartBeatIntervalConfig">
    <xs:sequence>
      <xs:element name="snmp-object" type="snmpObjectConfig" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="time-unit" type="heartBeatTimeUint"/>
  </xs:complexType>

  <xs:complexType name="heartBeatPullConfig">
    <xs:sequence>
      <xs:element name="hearbeat-ping-config" type="heartBeatPingConfig" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="heartBeatPingConfig">
    <xs:sequence>
      <xs:element name="snmp-object" type="snmpObjectConfig" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="propertyConfig">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="type" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="heartBeatTimeUint">
    <xs:restriction base="xs:string">
      <xs:enumeration value="nanoseconds"/>
      <xs:enumeration value="microseconds"/>
      <xs:enumeration value="seconds"/>
      <xs:enumeration value="minutes"/>
      <xs:enumeration value="hours"/>
      <xs:enumeration value="days"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== consultant-1379/o1-fm-transformation/o1-support-cbp-oi-fm-transformation-jar/src/main/resources/snmp-mediation-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<snmp-mediation-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:noNamespaceSchemaLocation="snmp-mediation-config.xsd">

   <network-element type="O1" version="1.0.0">

      <!-- configuration to retrieve alarm list from SNMP tables -->
      <alarms-get-config>
         <alarm-entry-config id="01">
            <!-- ERICSSON-ALARM-XPATH-MIB::eriAlarmXActiveAlarmTable -->
            <snmp-table oid=".1.3.6.1.4.1.193.183.6.1.3.5">
               <!-- filters on fields (read only following fields ) -->
               <!-- ERICSSON-ALARM-XPATH-MIB::eriAlarmXActiveMajorType -->
               <snmp-field oid=".1.3.6.1.4.1.193.183.6.1.3.5.1.2" />
               <!-- ERICSSON-ALARM-XPATH-MIB::eriAlarmXActiveMinorType -->
               <snmp-field oid=".1.3.6.1.4.1.193.183.6.1.3.5.1.3" />
               <!-- ERICSSON-ALARM-XPATH-MIB::eriAlarmXActiveSpecificProblem -->
               <snmp-field oid=".1.3.6.1.4.1.193.183.6.1.3.5.1.4" />
               <!-- ERICSSON-ALARM-XPATH-MIB::eriAlarmXActiveYangNodeInstance -->
               <snmp-field oid=".1.3.6.1.4.1.193.183.6.1.3.5.1.5" />
               <!-- ERICSSON-ALARM-XPATH-MIB::eriAlarmXActiveEventType -->
               <snmp-field oid=".1.3.6.1.4.1.193.183.6.1.3.5.1.6" />
               <!-- ERICSSON-ALARM-XPATH-MIB::eriAlarmXActiveEventTime -->
               <snmp-field oid=".1.3.6.1.4.1.193.183.6.1.3.5.1.7" />
               <!-- ERICSSON-ALARM-XPATH-MIB::eriAlarmXActiveProbableCause -->
               <snmp-field oid=".1.3.6.1.4.1.193.183.6.1.3.5.1.9" />
               <!-- ERICSSON-ALARM-XPATH-MIB::eriAlarmXActiveSeverity -->
               <snmp-field oid=".1.3.6.1.4.1.193.183.6.1.3.5.1.10" />
               <!-- ERICSSON-ALARM-XPATH-MIB::eriAlarmXActiveAdditionalText -->
               <snmp-field oid=".1.3.6.1.4.1.193.183.6.1.3.5.1.12" />
               <!-- ERICSSON-ALARM-XPATH-MIB::eriAlarmXActiveAdditionalInfo -->
               <snmp-field oid=".1.3.6.1.4.1.193.183.6.1.3.5.1.15" />
            </snmp-table>
         </alarm-entry-config>
      </alarms-get-config>

      <!-- configuration for heartbeat if mode=push the snmp-object is the object
  for set interval if mode=pull the snmp-object is the object for the ping
  keep-alive -->
      <heartbeat-push-config>
         <heartbeat-interval-config time-unit="seconds">
            <!-- heartbeat interval is pre-configured. To avoid errors, OID value
             equal to "0" prevent heartbeat interval configuration -->
            <snmp-object oid="0" />
         </heartbeat-interval-config>
      </heartbeat-push-config>

      <event-notification-defaults>
         <attribute name="sourceType">O1</attribute>
      </event-notification-defaults>

      <properties>
         <!-- SNMP Connection Default Parameters -->
         <property name="snmpRetries">1</property>    <!-- number of retries -->
         <property name="snmpTimeout">2000</property> <!-- snmpTimeout in milliseconds -->
         <property name="snmpTrapPort">162</property>
         <property name="snmpWriteCommunity">public</property>

         <!-- SNMP Object fot get last sequence number: eriAlarmXActiveLastSequenceNo -->
         <property name="lastSequenceNumberObject">ERICSSON-ALARM-XPATH-MIB::.1.3.6.1.4.1.193.183.6.1.3.3.0</property>

      </properties>
   </network-element>
</snmp-mediation-config>
